pipeline {
    agent any

    environment {
        VENV_DIR = "venv"
    }

    stages {
        stage('Clone Repo') {
            steps {
                git url: 'file:///var/lib/jenkins/workspace/ci-cd-flask
' // Or use a local GitHub clone
            }
        }

        stage('Set Up Python Environment') {
            steps {
                sh 'python3 -m venv $VENV_DIR'
                sh './$VENV_DIR/bin/pip install -r requirements.txt'
            }
        }

        stage('Run Tests') {
            steps {
                sh './$VENV_DIR/bin/python -m pytest || true'
            }
        }

        stage('Deploy App') {
            steps {
                sh './$VENV_DIR/bin/python app.py &'
            }
        }
    }
}
