pipeline {
    agent any

    stages {
        stage('Clone') {
            steps {
                git 'file:///home/cspl/Desktop/my-flask-app' // Or local path
            }
        }

        stage('Install') {
            steps {
                sh 'pip install -r requirements.txt'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests... (placeholder)'
            }
        }

        stage('Deploy') {
            steps {
                sh 'python app.py &'
            }
        }
    }
}
